pull_request_title: 'feat(localize): updated translation from Crowdin'
pull_request_labels:
  - crowdin
excluded_target_languages: ['ttm']
files:
  - source: /docs/locales/en/*.json
    translation: /docs/locales/%two_letters_code%/%original_file_name%
